# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI/dmfSettingsDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DMFSettingsDialog(object):
    def setupUi(self, DMFSettingsDialog):
        DMFSettingsDialog.setObjectName("DMFSettingsDialog")
        DMFSettingsDialog.resize(210, 10)
        self.verticalLayout = QtWidgets.QVBoxLayout(DMFSettingsDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(DMFSettingsDialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.discretizationPointsLineEdit = QtWidgets.QLineEdit(DMFSettingsDialog)
        self.discretizationPointsLineEdit.setObjectName("discretizationPointsLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.discretizationPointsLineEdit)
        self.label_2 = QtWidgets.QLabel(DMFSettingsDialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.upperLimitFactorLineEdit = QtWidgets.QLineEdit(DMFSettingsDialog)
        self.upperLimitFactorLineEdit.setObjectName("upperLimitFactorLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.upperLimitFactorLineEdit)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(DMFSettingsDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(DMFSettingsDialog)
        self.buttonBox.accepted.connect(DMFSettingsDialog.accept)
        self.buttonBox.rejected.connect(DMFSettingsDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(DMFSettingsDialog)

    def retranslateUi(self, DMFSettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        DMFSettingsDialog.setWindowTitle(_translate("DMFSettingsDialog", "DMF Settings"))
        self.label.setText(_translate("DMFSettingsDialog", "Discretization points:"))
        self.discretizationPointsLineEdit.setPlaceholderText(_translate("DMFSettingsDialog", "200"))
        self.label_2.setText(_translate("DMFSettingsDialog", "Upper Limit Factor:"))
        self.upperLimitFactorLineEdit.setPlaceholderText(_translate("DMFSettingsDialog", "2"))
