# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI/fluidParametersDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FluidParametersDialog(object):
    def setupUi(self, FluidParametersDialog):
        FluidParametersDialog.setObjectName("FluidParametersDialog")
        FluidParametersDialog.resize(300, 10)
        self.verticalLayout = QtWidgets.QVBoxLayout(FluidParametersDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(FluidParametersDialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.liquidSpecificMassLineEdit = QtWidgets.QLineEdit(FluidParametersDialog)
        self.liquidSpecificMassLineEdit.setObjectName("liquidSpecificMassLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.liquidSpecificMassLineEdit)
        self.label_2 = QtWidgets.QLabel(FluidParametersDialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.liquidKineticViscosityLineEdit = QtWidgets.QLineEdit(FluidParametersDialog)
        self.liquidKineticViscosityLineEdit.setObjectName("liquidKineticViscosityLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.liquidKineticViscosityLineEdit)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(FluidParametersDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(FluidParametersDialog)
        self.buttonBox.accepted.connect(FluidParametersDialog.accept)
        self.buttonBox.rejected.connect(FluidParametersDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(FluidParametersDialog)

    def retranslateUi(self, FluidParametersDialog):
        _translate = QtCore.QCoreApplication.translate
        FluidParametersDialog.setWindowTitle(_translate("FluidParametersDialog", "Fluid Parameters"))
        self.label.setText(_translate("FluidParametersDialog", "<html><head/><body><p>Specific Mass: (kg/m<span style=\" vertical-align:super;\">3</span>)</p></body></html>"))
        self.liquidSpecificMassLineEdit.setPlaceholderText(_translate("FluidParametersDialog", "998.2071"))
        self.label_2.setText(_translate("FluidParametersDialog", "<html><head/><body><p>Kinetic Viscosity: (m<span style=\" vertical-align:super;\">2</span>/s)</p></body></html>"))
        self.liquidKineticViscosityLineEdit.setPlaceholderText(_translate("FluidParametersDialog", "1.003e-06"))
