# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI/stepSizeDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StepSizeDialog(object):
    def setupUi(self, StepSizeDialog):
        StepSizeDialog.setObjectName("StepSizeDialog")
        StepSizeDialog.resize(200, 10)
        self.verticalLayout = QtWidgets.QVBoxLayout(StepSizeDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(StepSizeDialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.timeStepLineEdit = QtWidgets.QLineEdit(StepSizeDialog)
        self.timeStepLineEdit.setObjectName("timeStepLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.timeStepLineEdit)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(StepSizeDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(StepSizeDialog)
        self.buttonBox.accepted.connect(StepSizeDialog.accept)
        self.buttonBox.rejected.connect(StepSizeDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(StepSizeDialog)

    def retranslateUi(self, StepSizeDialog):
        _translate = QtCore.QCoreApplication.translate
        StepSizeDialog.setWindowTitle(_translate("StepSizeDialog", "Step Size"))
        self.label.setText(_translate("StepSizeDialog", "Time Step: (s)"))
        self.timeStepLineEdit.setPlaceholderText(_translate("StepSizeDialog", "0.005"))
